[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/alioygur/gores"
  version = "1.2.1"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "4.0.2"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/google/logger"
  version = "1.0.1"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.1"

[[constraint]]
  name = "github.com/gojektech/heimdall"
  version = "5.0.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/jinzhu/configor"
  version = "1.1.0"

[[constraint]]
  name = "gopkg.in/guregu/null.v3"
  version = "3.4.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"
