[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/alioygur/gores"
  version = "1.2.1"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "4.0.2"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.3.0"
